#!/bin/bash

/usr/local/bin/fluentd -c /fluent/fluent.conf -i \<match\ modaemon.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-modaemon-log'
'\</match\>'
'\<match\ apache.access\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-apache-access'
'\</match\>'
'\<match\ apache.error\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-apache-error'
'\</match\>'
'\<match\ apache.httpd.access\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-apache-httpd-access'
'\</match\>'
'\<match\ apache.httpd.error\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-apache-httpd-error'
'\</match\>'
'\<match\ supervisor.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-supervisor-log'
'\</match\>'
'\<match\ bundler.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-bundler-log'
'\</match\>'
'\<match\ startup.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-startup-log'
'\</match\>'
'\<match\ auth.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-auth-log'
'\</match\>'
'\<match\ nginx.access.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-nginx-access-log'
'\</match\>'
'\<match\ nginx.error.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-nginx-error-log'
'\</match\>'
'\<match\ rails_production.log\>'
'\	type\ remote_syslog'
'\	host\ $REMOTE_SYSLOG_HOST'
'\	port\ $REMOTE_SYSLOG_PORT'
'\	severity\ debug'
'\	program\ $MOCLOUD_LOG_STREAM-rails_production-log'
'\</match\>'
'
