#!/bin/bash

/usr/local/bin/fluentd -c /fluent/fluent.conf -i \<match\ modaemon.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-modaemon-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ apache.access\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-apache-access'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ apache.error\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-apache-error'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ supervisor.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-supervisor-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ bundler.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-bundler-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ startup.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-startup-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ auth.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-auth-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ nginx.access.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-nginx-access-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ nginx.error.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-nginx-error-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ rails_production.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-rails_production-log'
'\	auto_create_stream\ true'
'\</match\>'
'
