#!/bin/bash

/usr/local/bin/fluentd -c /fluent/fluent.conf -i \<match\ modaemon.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-modaemon-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ apache.access\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-apache-access'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ apache.error\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-apache-error'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ supervisor.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-supervisor-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ bundler.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-bundler-log'
'\	auto_create_stream\ true'
'\</match\>'
'\<match\ migration.log\>'
'\	type\ cloudwatch_logs'
'\	log_group_name\ $MOCLOUD_LOG_GROUP'
'\	log_stream_name\ $MOCLOUD_LOG_STREAM-migration-log'
'\	auto_create_stream\ true'
'\</match\>'
'
